Repository isabellegoralsky/cs130-project, pull requests merged in 2024-02, with the labels that each got.

#21 Added user functionality
  .env
  .gitignore
  index.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
  routes/userRoute.js
Labels: backend

#25 Added login and register user pages
  client/src/App.js
  client/src/components/LoginPage.js
  client/src/components/Navbar.js
  client/src/components/RegisterPage.js
Labels: functionality

#27 styling stuff
  client/public/GP-favicon.png
  client/public/index.html
  client/src/components/Carousel.js
  client/src/components/LoginPage.js
  client/src/components/LoginReg.css
  client/src/components/Navbar.css
  client/src/components/Navbar.js
  client/src/components/RegisterPage.js
  client/src/components/TeamPage.js
  client/src/components/Teams.css
Labels: styling
