Repository isabellegoralsky/cs130-project, pull requests merged in 2024-03, with the labels that each got.

#46 Template schema+endpoints
  index.js
  models/Template.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
  routes/profileRoute.js
  routes/userRoute.js
Labels: database, backend

#47 Ig styling2
  client/src/App.js
  client/src/components/Footer.js
  client/src/components/LoginReg.css
  client/src/components/Navbar.css
  client/src/components/ProfilePage.css
  client/src/components/ProfilePage.js
  client/src/components/Teams.css
  node_modules/.package-lock.json
  package-lock.json
  package.json
Labels: styling

#51 styling stuff for the pages
  client/src/components/Carousel.js
  client/src/components/Goal.css
  client/src/components/Goal.js
  client/src/components/GoalsPage.css
  client/src/components/GoalsPage.js
  client/src/components/LoginPage.js
  client/src/components/LoginReg.css
  client/src/components/Navbar.css
  client/src/components/Navbar.js
  client/src/components/ProfilePage.css
  client/src/components/TeamPage.js
  client/src/components/Teams.css
Labels: styling

#49 Add get/edit user endpoints
  routes/userRoute.js
Labels: backend

#62 Goal and Picture backend
  server/package-lock.json
  server/package.json
  server/src/index.js
  server/src/middleware/auth.js
  server/src/models/Goal.js
  server/src/models/Picture.js
  server/src/models/User.js
  server/src/routes/goalRoute.js
  server/src/routes/pictureRoute.js
  server/src/routes/userRoute.js
Labels: backend

#56 feed page styling
  client/public/gympals_logo.png
  client/src/components/FeedPage.css
  client/src/components/FeedPage.js
  client/src/components/Navbar.css
  client/src/components/Navbar.js
Labels: styling

#77 Update goal
  server/src/models/Goal.js
  server/src/models/Post.js
  server/src/models/TeamGoal.js
  server/src/models/Template.js
  server/src/models/User.js
  server/src/routes/goalRoute.js
  server/src/routes/postRoute.js
  server/src/routes/teamGoalRoute.js
Labels: backend
